### ISSUE TITLE
T060101c - clarity

### ISSUE THREAD

**Issue by band** [orcmid/nfoTools#88]
This is an informative and detailed description.

Two things struck me as I read it:

1. In the first part of this sentence:
"There is not far to get without having software that compiles C Language files into programs that run on the computer."
"There is not far to get without ..." is a bit clunky. I had to read it twice to understand it.
Suggestion:
"One of the first tools needed is software that compiles C Language files ...."

2. I may have missed this, but what is the difference between "C" and "Clean C"? Maybe that is described elsewhere in this project?

**Comment by orcmid** [comment]
Thanks @band.  I think I have improved those areas.
